language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - travis_retry python setup.py install
  - travis_retry pip install -U -r dev-requirements.txt

script: python setup.py test
